services:
  - type: web
    name: shl-flask-api
    env: python
    plan: free
    buildCommand: |
      pip install --no-cache-dir numpy
      pip install --no-cache-dir -r requirements.txt
    startCommand: python api.py
    envVars:
      - key: PORT
        value: 5000  # optional fallback; Render auto-assigns a PORT
